### ISSUE TITLE
kernel，kernel-devel，kernel-headers版本一致问题

### ISSUE THREAD

**Issue by jinwyp** [UJX6N/bbrplus#1]
由于bbs plus 原版 安装后 内饰是bbrplus 4.14 

但在安装 kernel-devel，kernel-headers 后版本是3.xx 不一致 导致 WireGuard 无法安装

能否把同样版本的bbrplus 4.14   kernel-devel，kernel-headers  编译出来 

现在只能装回原版bbr 才能装 WireGuard 

https://github.com/chiakge/Linux-NetSpeed
https://github.com/ylx2016/Linux-NetSpeed

相关脚本 都是用这种一键安装的bbr plus  4.14 结果kernel-devel，kernel-headers 和 kernel版本不一致

同样 其他4.19 5.4版本也最好提供 kernel-devel，kernel-headers 同样版本的，否则都不一致 无法安装 WireGuard

**Comment by UJX6N** [comment]
> 
> 
> 由于bbs plus 原版 安装后 内饰是bbrplus 4.14
> 
> 但在安装 kernel-devel，kernel-headers 后版本是3.xx 不一致 导致 WireGuard 无法安装
> 
> 能否把同样版本的bbrplus 4.14 kernel-devel，kernel-headers 编译出来
> 
> 现在只能装回原版bbr 才能装 WireGuard
> 
> https://github.com/chiakge/Linux-NetSpeed
> https://github.com/ylx2016/Linux-NetSpeed
> 
> 相关脚本 都是用这种一键安装的bbr plus 4.14 结果kernel-devel，kernel-headers 和 kernel版本不一致
> 
> 同样 其他4.19 5.4版本也最好提供 kernel-devel，kernel-headers 同样版本的，否则都不一致 无法安装 WireGuard

hi，你好。都是提供了devel和headers的，比方4.14.222，对于centos 7提供的二进制包有

CentOS-7_Required_kernel-bbrplus-4.14.222-1.bbrplus.el7.x86_64.rpm
CentOS-7_Optional_kernel-bbrplus-devel-4.14.222-1.bbrplus.el7.x86_64.rpm
CentOS-7_Optional_kernel-bbrplus-headers-4.14.222-1.bbrplus.el7.x86_64.rpm
